select * from MEMBER_INFO;
select * from BOARD;            

select * from SEAT;
select * from RESERVATION;

INSERT INTO MEMBER_INFO(ID, PASSWORD, NAME, ADDRESS)
VALUES();

INSERT ITNO BOARD(, BOARD_ID, TITLE, SUBSTANCE)
VALUES();

INSERT INTO SEAT(, SEAT_ID, SEAT_NUM)
VALUES();

INSERT INTO RESERVATION(, RE_ID, RE_NUM)
VALUES();